server:
    port: 8081
    servlet:
        context-path: /api

spring:
    application:
        name: accounts-ms
    datasource:
        url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:devsu_accounts_db}
        username: ${DATABASE_USER:postgres}
        password: ${DATABASE_PASSWORD:juancuero}
        driver-class-name: org.postgresql.Driver
    jpa:
        generate-ddl: true
        show-sql: false
        properties:
            hibernate:
                format_sql: true
                jdbc:
                    time_zone: America/Bogota
        hibernate:
            ddl-auto: create
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    jackson:
        property-naming-strategy: SNAKE_CASE
    kafka:
        bootstrap-servers: ${KAFKA_BROKER_URL:localhost:9092}
        consumer:
            group-id: "accounts-service-group"

ms:
    users:
        name: "ms-users"
        url: http://localhost:8080
